def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "maven3914"
        jdk "jdk17"
    }
    
    environment {
        CLUSTER = "devopsappprod"
        SERVICE = "devopstask-service-prod"
    }

    stages {
        stage("Deploy to Prod ECS"){
            steps{
                withAWS(credentials: 'awscreds', region : 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE} --force-new-deployment'
                }
            }
        }
    }
        
     post {
        always {
            echo 'Slack Notification'
            slackSend channel: '#jenkins',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n Shadow fmm: ${env.BUILD_URL}"
        }
        }
}